### ISSUE TITLE
Version 0.3.0 not yet published to the terraform registry?

### ISSUE THREAD

**Issue by pmdematagoda** [Backblaze/terraform-provider-b2#10]
I just noticed that version 0.3.0 was released almost a week ago, which had the support for configuring server side encryption on buckets that I was looking for, but I noticed that this version hasn't been published to the terraform registry yet. Was this version going to be published?

**Comment by ppolewicz** [comment]
There is a problem with the continous deployment server which is unable to upload the new version to the registry. We are investigating it.

**Comment by mlech-reef** [comment]
Version 0.4.0 has been released and it's available in [Terrafrom Registry](https://registry.terraform.io/providers/Backblaze/b2/latest).
![image](https://user-images.githubusercontent.com/63924630/114077288-e9899380-98a7-11eb-9a4b-195f156fcee2.png)

**Comment by pmdematagoda** [comment]
Used the new release, works great, thank you :)
