### ISSUE TITLE
Do not use Ubuntu 16.04 runner in CI/CD as it is deprecated

### ISSUE THREAD

**Issue by mlech-reef** [Backblaze/terraform-provider-b2#16]
Ubuntu 16.04 is now deprecated in GitHub Actions.
We use it now to create a binary with `pyinstaller` in order to use older `glibc` version so our bundle works even on older OSes (see [this](https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible) for details).

We can either:
* use Ubuntu 18.04 and drop support for OSes with older `glibc`
* Use Docker runner with Ubuntu 16.04

**Comment by mszumocki-reef** [comment]
Switched to ubuntu-latest, should not matter anymore with static Python bindings build.
