### ISSUE TITLE
Add support for Apple M1 chip

### ISSUE THREAD

**Issue by cfs100** [Backblaze/terraform-provider-b2#18]
I am currently unable to use Terraform due to this error.

```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/backblaze/b2 v0.5.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

My environment:

-macOS Big Sur (version 11.2.2)
-MacBook Air (M1, 2020)
-Chip: Apple M1

**Comment by mszumocki-reef** [comment]
We could crosscompile the Go part of the provider using existing GitHub runners but provider would still require Rosetta installed to execute Python bindings part (this cannot really be fixed until we can get runners on M1). 
Would that solve your issue @cfs100 ?

**Comment by cfs100** [comment]
Hi @mszumocki-reef, I believe it would.

**Comment by mszumocki-reef** [comment]
@cfs100 Please try the 0.6.0 release.
