### ISSUE TITLE
Possibility of a Pulumi provider?

### ISSUE THREAD

**Issue by AgrimPrasad** [Backblaze/terraform-provider-b2#2]
Thanks for creating this Terraform B2 provider!

We are considering using B2 as a cost-effective object storage solution for storage needs as we are currently using GCS buckets with a very high number of write operations per month.

As we are currently provisioning infrastructure at our company using [Pulumi](https://www.pulumi.com/) it would be great to provision Backblaze B2 Buckets using Pulumi too. Most Pulumi providers are based on Terraform providers already, so it should be relatively straightforward to convert this Terraform provider into a Pulumi provider. Pulumi Developers are active on https://slack.pulumi.com/ for advice.

**Comment by ppolewicz** [comment]
Hey @AgrimPrasad,

Please [contact B2 sales team](https://www.backblaze.com/b2/contact-sales.html) to discuss your case. [Pricing](https://www.backblaze.com/b2/cloud-storage-pricing.html) says you might save 💰on storage and [migration](https://www.backblaze.com/b2/solutions/datatransfer/cloud-to-cloud.html) says B2 might even cover the cost of your transiton between clouds. More specifically for your company, GCS [charges](https://cloud.google.com/storage/pricing#operations-by-class) for the write operations you've mentioned while b2_upload_file in B2 [is free](https://www.backblaze.com/b2/b2-transactions-price.html)! Actually this is what made me fall in love with B2 many years ago - they have pushed the limit on how cheap storage can be, making it possible for anyone to store whatever they want in a durable manner for as little cost as practical (as close to free as possible).

Pulumi looks cool, so if lack of B2 support in it is the main blocker for you, then I'm sure the sales team will help arrange something.

**Comment by AgrimPrasad** [comment]
> Hey @AgrimPrasad,
> 
> Please [contact B2 sales team](https://www.backblaze.com/b2/contact-sales.html) to discuss your case. [Pricing](https://www.backblaze.com/b2/cloud-storage-pricing.html) says you might save 💰on storage and [migration](https://www.backblaze.com/b2/solutions/datatransfer/cloud-to-cloud.html) says B2 might even cover the cost of your transiton between clouds. More specifically for your company, GCS [charges](https://cloud.google.com/storage/pricing#operations-by-class) for the write operations you've mentioned while b2_upload_file in B2 [is free](https://www.backblaze.com/b2/b2-transactions-price.html)! Actually this is what made me fall in love with B2 many years ago - they have pushed the limit on how cheap storage can be, making it possible for anyone to store whatever they want in a durable manner for as little cost as practical (as close to free as possible).
> 
> Pulumi looks cool, so if lack of B2 support in it is the main blocker for you, then I'm sure the sales team will help arrange something.

Thanks for the reply. We switched to Digitalocean Spaces, which already supports Pulumi and also has free API calls + S3 API compatibility.

**Comment by ppolewicz** [comment]
Ok, thanks for getting back to me.
BTW Spaces costs $0.02/GiB/mo, while B2 is at $0.005/GiB/mo, but I guess if your objects are small, that may be irrelevant

**Comment by antholeole** [comment]
+1 on this issue. The only reason I use s3 right now is because of its pulumi integrations. I want to switch over to B2, but it's a tough sell not being able to work it into my current IaC directly. I'm a small fish though!
