### ISSUE TITLE
Don't fail deleting an already deleted bucket

### ISSUE THREAD

**Issue by nhoughto** [Backblaze/terraform-provider-b2#23]
Currently when `terraform destroy`ing a terraform managed bucket, the provider fails with an error if the bucket has already been deleted.

Error is : `Error: No such bucket: 629955074482c...`

Since we are _trying_ to delete the bucket, and the bucket is already deleted a more user-friendly behaviour would be to just complete successfully, this is the default behaviour for many providers including the AWS S3 bucket resource. At the moment the workaround is to `terraform state rm..` the resource manually to fix the problem, this is obviously not ideal.

The reason the bucket is deleted outside of terraform is related to: https://github.com/Backblaze/terraform-provider-b2/issues/22 so a solution to either would work =)

**Comment by nhoughto** [comment]
Ah ok, so the situation is im running a destroy (after apply) and in between the two commands the bucket has been deleted manually.

I guess resource read should return an empty state rather than an exception? I can’t remember what the terraform interface for this scenario expects.

The reason it’s doing a read before destroy is to figure out what to destroy I suppose.

**Comment by mszumocki-reef** [comment]
I'll be releasing that change in 0.7.1
