### ISSUE TITLE
Error while creating a bucket "Error: error getting lifecycle_rules"

### ISSUE THREAD

**Issue by AMKamel** [Backblaze/terraform-provider-b2#28]
I got this error Error: error getting lifecycle_rules on version 0.7.1

While the code creating bucket was
```
resource "b2_bucket" "bucket" {
  bucket_name = var.bucket_name
  bucket_type = var.bucket_type
}
```

**Comment by mszumocki-reef** [comment]
I'm getting  b2sdk.exception.DuplicateBucketName: Bucket name is already in use now.
