### ISSUE TITLE
Issue running terraform apply

### ISSUE THREAD

**Issue by FreedomBen** [Backblaze/terraform-provider-b2#30]
Hello, apologies if there's a better place for this question.  Docs are pretty limited at this point so I might just be missing something simple.  If I can get this working I will send a PR with some docs to help the next person.

Using the latest terraform release (1.1.4) and latest terraform-provider-b2 (0.7.1).  Works fine until `terraform apply`, then it bombs trying to access the b2 account before creating anything with:

```
requests.exceptions.MissingSchema: Invalid URL 'us-west-002/b2api/v2/b2_authorize_account': No schema supplied. Perhaps you meant http://us-west-002/b2api/v2/b2_authorize_account?
```

That exception happens a bunch of times in `requests/models.py` , `prepare_url` line 390.

Full trace:

```
│ Error: Traceback (most recent call last):                                                  
│   File "b2sdk/b2http.py", line 53, in _translate_errors                                                                                                                                 
│   File "b2sdk/b2http.py", line 303, in do_post                                             
│   File "requests/sessions.py", line 590, in post                                           
│   File "requests/sessions.py", line 528, in request                                        
│   File "requests/sessions.py", line 456, in prepare_request
│   File "requests/models.py", line 316, in prepare                           
│   File "requests/models.py", line 390, in prepare_url     
│ requests.exceptions.MissingSchema: Invalid URL 'us-west-002/b2api/v2/b2_authorize_account': No schema supplied. Perhaps you meant http://us-west-002/b2api/v2/b2_authorize_account?
```

I wondered if my creds weren't being properly picked up from env vars, but starting two new shells gives a different error that goes away after exporting the variables:  `B2 Application Key and Application Key ID must be provided` .  Also the b2 CLI tool is working perfectly fine in the same shell.

It kind of seems like it's a b2 sdk issue and that the b2 sdk isn't properly putting `https://` on the url but, looking at the code it seems like it is.

If helpful, here's my terraform code.  The terraform and provider block came straight from the examples:

```terraform
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    b2 = {
      source = "Backblaze/b2"
    }
  }
}

provider "b2" {
}

resource "b2_bucket" "cvh_recordings" {
  bucket_name = "cvh-recordings-staging-t1"
  bucket_type = "allPrivate"

  default_server_side_encryption {
    algorithm = "AES256"
    mode      = "SSE-B2"
  }

  lifecycle_rules {
    file_name_prefix              = ""
    days_from_hiding_to_deleting  = "30"
    days_from_uploading_to_hiding = "30"
  }

  file_lock_configuration {
    is_file_lock_enabled = false
    default_retention {
      mode   = "none"
      period {
        duration = "90"
        unit     = "days"
      }
    }
  }
}

```

**Comment by ppolewicz** [comment]
It looks like a bug in the terraform provider or b2-sdk-python, or somewhere in between!

**Comment by mszumocki-reef** [comment]
HGi, mode = "none" is not valid for default_retention block (it can be "governance" or "compliance").
Sample works for me with default_retention block removed, could you tell me if you perhaps you're trying to access to manage a bucket created in EU region using a US region configured key or vice versa?

**Comment by FreedomBen** [comment]
This looks to be working now in v0.8.0 :partying_face:   Will follow up if I run into it again, thanks!
