### ISSUE TITLE
Add ARM Support for Provider

### ISSUE THREAD

**Issue by jstewart612** [Backblaze/terraform-provider-b2#34]
Hello.  I am interested in having ARM support: https://github.com/Backblaze/terraform-provider-b2/issues/1#issuecomment-772606604

**Comment by ppolewicz** [comment]
Hello

can you describe the use case you have? Are you running terraform on r-pi? Why?

**Comment by flaudisio** [comment]
Hello! I'm interested too; I'm running Atlantis+Terraform on Oracle's [Ampere/ARM instances](https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm#flexible) - and I'm probably going to deploy on AWS Graviton instances in the near future, so having support on ARM would be great! Please let me know if I can help testing the provider on these platforms.

**Comment by ppolewicz** [comment]
are you installing it directly on the machine or is it running in a container?

**Comment by flaudisio** [comment]
It's running in a container.

**Comment by nwholloway** [comment]
I would also like to have ARM support.

I am using Terraform to manage my personal AWS resources, and would like to start using Backblaze B2.  One of the ways I run simple updates is to SSH to a Pi 4, rather than the Linux laptop.

**Comment by iamkhalidbashir** [comment]
arm support ?

**Comment by iamkhalidbashir** [comment]
I see that it publishs arm64 binaries but terraform dosent use it

**Comment by vbaltrusaitis-reef** [comment]
https://github.com/Backblaze/terraform-provider-b2/pull/62 fixes the issue, `v0.8.6` arm64 binaries should be working. Let me know if you encounter any further problems.

**Comment by ashfame** [comment]
@vbaltrusaitis-reef Filed a possibly related issue - #76
