### ISSUE TITLE
Unable to configure "Keep only the last version of the file" lifecycle rule

### ISSUE THREAD

**Issue by jglopez** [Backblaze/terraform-provider-b2#46]
If a B2 bucket has its lifecycle settings configured to "Keep only the last version of the file" via the web interface:
![image](https://github.com/Backblaze/terraform-provider-b2/assets/18109684/344c8efc-8e63-41c6-be69-9b861a3fa0c8)

Then the provider will unnecessarily require that `file_name_prefix` be defined and will always instead want to create a custom lifecycle rule.
Error from terraform plan:
```
╷
│ Error: Missing required argument
│ 
│   on redacted.tf line 6, in resource "b2_bucket" "redacted":
│    6:   lifecycle_rules {
│ 
│ The argument "file_name_prefix" is required, but no definition was found.
╵
```

### Steps to reproduce
1. Create B2 bucket [via web interface](https://secure.backblaze.com/b2_buckets.htm)
2. Configure lifecycle settings: Keep only the last version of the file
3. Import B2 bucket into Terraform state: `terraform import b2_bucket.example [bucket_id]`
4. Run `terraform plan`
5. See that terraform requires that `file_name_prefix` is defined

### Version info
```shell
$ terraform -v
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/backblaze/b2 v0.8.4
```

**Comment by jglopez** [comment]
Whoops! Sorry, just realized this was already reported 🤦

Duplicate of #3

**Comment by colans** [comment]
Even with better documentation, this is still really broken.  See https://github.com/Backblaze/terraform-provider-b2/issues/85 .

**Comment by mlech-reef** [comment]
As stated in #3, `fileNamePrefix` is required to be an empty string in order to apply the rules to every file in the bucket - that why this parameter is required which is aligned with the B2 API
