### ISSUE TITLE
Bucket region / S3 API endpoint?

### ISSUE THREAD

**Issue by bradenmacdonald** [Backblaze/terraform-provider-b2#5]
When creating a bucket with Terraform, in order for my application to use it, I need to know the S3 compatible API endpoint, like `s3.us-west-000.backblazeb2.com`. However, I can't seem to find any way to get the `region` or the `endpoint` URL using this provider. Could that please be added (or documented) in the future?

**Comment by mlech-reef** [comment]
Hi!

It is not something B2 API is providing right now. You can either try to programmatically construct the URL or try to use S3 compatible API from the beginning with the ``aws`` provider, but it has never been tested.

Best regards,
Maciej Lech

**Comment by nilayp** [comment]
Branden,
(Nilay from Backblaze here.)

Thanks for the feedback. We are investigating the correct way to solve this.

-- Nilay

**Comment by bradenmacdonald** [comment]
Great, thanks @nilayp.

**Comment by ibayer** [comment]
My test with your provider have been successful so far but not I'm suck regarding the s3 endpoint.

> You can either try to programmatically construct the URL or try to use S3 compatible API from the beginning with the aws provider, but it has never been tested.

Can you expand a bit on how to construct the URL?

Using the web interface I can see that my buckets always have endpoint ` s3.us-west-000.backblazeb2.com `
is this part of the endpoint static?

**Comment by ppolewicz** [comment]
We will do it the right way - terraform provider will output the S3 endpoint correctly, but as far as I heard, it is not really static, but it's always the same for your account, meaing that (unless something changes in the future) as long as you stay with the same account, you'll have the same S3 endpoint. You could try using that until we release a new version.

**Comment by mlech-reef** [comment]
As an addition to the @ppolewicz comment, an algorithm how to construct the S3 URL is posted in Backblaze/b2-sdk-python#200

**Comment by mlech-reef** [comment]
S3 API URL is now available in recently released 0.4.0 via `b2_account_info` data source.

**Comment by ibayer** [comment]
@mlech-reef Thanks for adding this. Can you add an example?

**Comment by mlech-reef** [comment]
Here you have.

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    b2 = {
      source = "Backblaze/b2"
    }
  }
}

provider "b2" {
}

data "b2_account_info" "example" {
}

output "account_info_s3_api_url" {
  value = data.b2_account_info.example.s3_api_url
}
```

```
...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

account_info_s3_api_url = "https://s3.us-west-000.backblazeb2.com"
```

**Comment by ibayer** [comment]
@mlech-reef Works great, thanks a lot!
