### ISSUE TITLE
Feature Request: Retrieve Bucket URL

### ISSUE THREAD

**Issue by jzandbergen** [Backblaze/terraform-provider-b2#56]
#### Description
The current `b2_bucket` Terraform resource lacks the capability to retrieve the URL for the bucket. This feature is essential for users who need easy access to their buckets.

#### Proposed Implementation
Add a new attribute or method to the `b2_bucket` resource that allows users to retrieve the URL of the bucket.

#### Example
```hcl
resource "b2_bucket" "example" {
  bucket_name = "my_bucket"
  bucket_type = "allPrivate"
}

output "bucket_url" {
  value = b2_bucket.example.bucket_url
}
```

#### Additional Information

- This enhancement will improve user experience and provide a convenient way to access bucket URLs programmatically.

**Comment by ppolewicz** [comment]
I think bucket url is [b2_account_info](https://github.com/Backblaze/terraform-provider-b2/blob/master/docs/data-sources/account_info.md#b2_account_info-data-source),download_url + '/' + [b2_bucket](https://github.com/Backblaze/terraform-provider-b2/blob/master/docs/data-sources/bucket.md#b2_bucket-data-source).bucket_name ? Or do you mean something else?
