### ISSUE TITLE
bucket encryption

### ISSUE THREAD

**Issue by keerts** [Backblaze/terraform-provider-b2#7]
This module is pure gold, we are using it for a complex offsite-backup solution. It saves a lot of manual configuration work.

I have a question on bucket options: Can bucket encryption be enabled at creation?

**Comment by mlech-reef** [comment]
Hi. Nice to hear that the provider helps you with your backup solution.

Server-side-encryption is a new feature and we are preparing to extend the SDK (Backblaze/b2-sdk-python#203) to support it, which this provider uses under the hood. When it's done, we will have this functionality in the provider as well.

**Comment by nilayp** [comment]
@keerts - Nilay from Backblaze here. I'd love to learn more about how you are using Terraform for your "complex offsite backup solution". Would you mind sharing your story either here or happy to take it offline too.

I'm so glad to hear the module helped you!

-- Nilay

**Comment by keerts** [comment]
Nilay,

I'd be happy to share how our setup works. We have many projects in Google Cloud with various database setups as well as data that is stored in GCS. All of these projects are in some way configured to backup that data to a bucket (or secondary buckets in the case of GCS). All of these backup buckets are synced to Backblaze in real time using cloud functions. The correct configuration of these cloud functions includes a key setup which is (was!) very error prone and labor intensive. This is where your module shines and is of tremendous help to us. We can now automatically configure application-keys in secret manager:

```
resource "b2_bucket" "b2-bucket" {
  for_each = var.backups
  bucket_name = "${var.project-id}-${each.key}"
  bucket_type = "allPrivate"
  lifecycle {
    prevent_destroy = true
  }
}

resource "b2_application_key" "b2-application-key" {
  for_each = var.backups
  key_name = "${var.project-id}-${each.key}"
  bucket_id = b2_bucket.b2-bucket[each.key].id
  capabilities = [...]
}

resource "google_secret_manager_secret" "secret-application-key" {
  for_each = var.backups
  secret_id = "offsite-backup_b2-application-key-${b2_application_key.b2-application-key[each.key].application_key_id}"
}

resource "google_secret_manager_secret_version" "secret-version-basic" {
  for_each = var.backups
  secret = google_secret_manager_secret.secret-application-key[each.key].id
  secret_data = b2_application_key.b2-application-key[each.key].application_key
}
```
Important note: your application keys now reside in Terraform state as well: you need to deal with this fact!
 
The second great thing is that we can now configure backup buckets with the strict regulations that we have around retention time (GDPR etc related) using the lifecycle_rules.

**Comment by akooms** [comment]
@keerts - Amrit here from the Product Marketing team at Backblaze. Thanks for sharing that info, we're excited to hear that our provider is serving you well and saving you from manual config work. Would you be open to us sharing your story and use-case as a feature on our blog? If so, happy to move forward in this thread or take it offline via email. 

Thanks!

Amrit

**Comment by keerts** [comment]
Sure, happy to. Let's take it offline. Just dropped you a message on LinkedIn.

**Comment by mlech-reef** [comment]
SSE-B2 is available in 0.4.0.

Support for SSE-C will be implemented when the SDK supports it.

**Comment by keerts** [comment]
That's great, thanks!

**Comment by keerts** [comment]
Upgraded to version 0.4.0 and tested it, works like a charm!

**Comment by mszumocki-reef** [comment]
SSE-C encryption on file level is now supported in 0.6.0

**Comment by nilayp** [comment]
@keerts - We published your story today, https://www.backblaze.com/b2/case-studies/avisi/. 
So great!! Thanks for sharing with us and the Backblaze community.

**Comment by keerts** [comment]
> @keerts - We published your story today, https://www.backblaze.com/b2/case-studies/avisi/.
> So great!! Thanks for sharing with us and the Backblaze community.

Great! Happy to share.
