### ISSUE TITLE
With unverified email, creating bucket gives 500 "internal incident" error

### ISSUE THREAD

**Issue by nfagerlund** [Backblaze/terraform-provider-b2#71]
Note: This is probably a bug with the python SDK rather than the provider's Go code, but I'm not in a spot to spin up a python dev environment to check.

If your Backblaze user account's email is not yet verified, you can't create any b2 buckets. UI shows this by disabling the create button. (The UI text seems to indicate this restriction is meant for public buckets, but it affects private too.)

But if you try to create a bucket via the provider, you get "b2sdk.exception.ServiceError: 500 internal_error internal incident":

```
b2_bucket.testtesttest: Creating...
b2_bucket.testtesttest: Still creating... [10s elapsed]
╷
│ Error: Traceback (most recent call last):
│   File "b2_terraform/provider_tool.py", line 527, in run_command
│   File "b2_terraform/provider_tool.py", line 131, in run
│   File "b2_terraform/provider_tool.py", line 231, in resource_create
│   File "logfury/_logfury/trace_call.py", line 86, in wrapper
│   File "b2sdk/api.py", line 242, in create_bucket
│   File "b2sdk/session.py", line 152, in create_bucket
│   File "b2sdk/session.py", line 445, in _wrap_default_token
│   File "b2sdk/session.py", line 451, in _wrap_token
│   File "b2sdk/session.py", line 466, in _reauthorization_loop
│   File "b2sdk/session.py", line 456, in _api_token_callback
│   File "b2sdk/raw_api.py", line 458, in create_bucket
│   File "b2sdk/raw_api.py", line 413, in _post_json
│   File "b2sdk/b2http.py", line 276, in post_json_return_json
│   File "b2sdk/b2http.py", line 235, in post_content_return_json
│   File "b2sdk/b2http.py", line 489, in _translate_and_retry
│   File "b2sdk/b2http.py", line 397, in _translate_errors
│ b2sdk.exception.ServiceError: 500 internal_error internal incident
│
│
│   with b2_bucket.testtesttest,
│   on main.tf line 16, in resource "b2_bucket" "testtesttest":
│   16: resource b2_bucket "testtesttest" {
```

This sent me on like a 40-minute run-around. It would be much more helpful to have a dedicated error message for "gotta verify".

**Comment by mjurbanski-reef** [comment]
This problem has been since addressed on API side.

Error codes `email_not_verified` and `no_payment_history` should be now properly displayed instead of `internal_error`.
