### ISSUE TITLE
cors_rules.allowed_operations are not stable

### ISSUE THREAD

**Issue by cinemast** [Backblaze/terraform-provider-b2#74]
Hi!

I define a bucket with cors rules using the following:

```
resource "b2_bucket" "media_bucket" {
  bucket_name = "example-${terraform.workspace}"
  bucket_type = "allPrivate"
  cors_rules {
    allowed_operations = [ "s3_put", "s3_head", "s3_get" ]
    allowed_origins = [ "https://app.${local.env[terraform.workspace].domain}", "http://localhost:5173"]
    cors_rule_name = "example-cors-${terraform.workspace}"
    max_age_seconds = 60
  }
}
```

It updates as expected, however, if I run again using `terraform apply` I again get the same change suggested 

```
resource "b2_bucket" "media_bucket" {
        id          = "<id>"
        # (7 unchanged attributes hidden)

      ~ cors_rules {
          ~ allowed_operations = [
              - "s3_head",
                "s3_put",
              + "s3_head",
                "s3_get",
            ]
            # (5 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }
```

Which should be a no-op.

**Comment by vbaltrusaitis-reef** [comment]
Thank you for the report. I can reproduce the problem and will work on fixing it. In the meantime, as a workaround you can reorder `allowed_operations` to `[ "s3_head", "s3_put", "s3_get" ]`.

**Comment by cinemast** [comment]
I tried that already, sadly with the same result.

**Comment by cinemast** [comment]
Any chance you could craft a release for this fix?

**Comment by mlech-reef** [comment]
@cinemast a new release is going to be created in upcoming days

**Comment by mlech-reef** [comment]
https://github.com/Backblaze/terraform-provider-b2/releases/tag/v0.9.0

**Comment by cinemast** [comment]
Thank you!
