### ISSUE TITLE
bad CPU type in executable (arm M3 support)

### ISSUE THREAD

**Issue by ashfame** [Backblaze/terraform-provider-b2#76]
Hello,

I tried creating a b2_bucket resource on Apple M3 chip, `terraform plan` shows output as expected but `terraform apply` throws this error:

```
│ Error: fork/exec /var/folders/z2/tm18d24j05308d97883ph4kh0000gn/T/py-terraform-provider220669967: bad CPU type in executable
│
│   with b2_bucket.testbucket,
│   on backblaze.tf line 14, in resource "b2_bucket" "testbucket":
│   14: resource "b2_bucket" "testbucket" {
```

Neither have rosetta installed, nor have the intention of installing it.

Did verify that arm64 build is what's installed under provider:

```
ashfame@ashfame-m3max terraform % file $(which terraform)
/opt/homebrew/bin/terraform: Mach-O 64-bit executable arm64
ashfame@ashfame-m3max terraform % uname -m
arm64
ashfame@ashfame-m3max terraform % ls -h .terraform/providers/registry.terraform.io/backblaze/b2/0.8.12/
darwin_arm64
```

**Comment by mlech-reef** [comment]
Switching to `macos-14` runner should solve the problem as previously used `macos-13-large` is Intel not ARM.

Now the architecture is correct:
```
~/work/terraform-provider-b2/terraform-provider-b2/python-bindings ~/work/terraform-provider-b2/terraform-provider-b2
177 INFO: PyInstaller: 6.8.0, contrib hooks: 2024.8
177 INFO: Python: 3.9.13
188 INFO: Platform: macOS-14.6.1-arm64-arm-64bit
```

Best regards,
Maciek

**Comment by ashfame** [comment]
@mlech-reef Still no new release?

**Comment by metadaddy** [comment]
@ashfame It looks like [0.9.0](https://github.com/Backblaze/terraform-provider-b2/releases/tag/v0.9.0), released Oct 20 2024, fixes this.
